# Generated by Django 5.0.3 on 2024-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.FileField(default='chat/img/user_image.jpg', upload_to='chat/img/'),
        ),
    ]
